/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Diorama.gltf
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Diorama(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('static/Diorama/Diorama.gltf')
  const { actions } = useAnimations(animations, group)
  //console.log(actions)
  useEffect(()=>{
    actions.SunCycle.play()
    actions.Walk.play()
    console.log(actions)
  },[actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-0.02, 1.2, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="metarig" position={[0.12, 0.33, -4.82]} scale={2.13}>
          <primitive object={nodes.spine004} />
          <skinnedMesh name="Jaguar" geometry={nodes.Jaguar.geometry} material={materials.TieDyeJaguar} skeleton={nodes.Jaguar.skeleton} />
        </group>
        <group name="Original" position={[-0.01, 1.89, -10.71]} rotation={[-3.01, 0.81, Math.PI]} scale={3.64}>
          <mesh name="Icosphere026" geometry={nodes.Icosphere026.geometry} material={nodes.Icosphere026.material} position={[1.24, 5.1, -0.85]} scale={[1.64, 1.41, 1.64]} />
          <mesh name="Icosphere027" geometry={nodes.Icosphere027.geometry} material={nodes.Icosphere027.material} position={[-0.7, 4.85, -0.04]} rotation={[Math.PI, -0.79, Math.PI]} />
          <mesh name="Icosphere028" geometry={nodes.Icosphere028.geometry} material={nodes.Icosphere028.material} position={[1.42, 5.31, 1.66]} rotation={[0, 0.43, -Math.PI]} scale={[1, 0.86, 1]} />
          <mesh name="Icosphere029" geometry={nodes.Icosphere029.geometry} material={nodes.Icosphere029.material} position={[1.67, 4.57, 0.54]} rotation={[-Math.PI, 0.43, -Math.PI]} scale={[0.61, 0.52, 0.61]} />
          <mesh name="Icosphere030" geometry={nodes.Icosphere030.geometry} material={nodes.Icosphere030.material} position={[2.21, 4.5, -0.67]} rotation={[-Math.PI, 0.43, -Math.PI]} scale={[0.61, 0.52, 0.61]} />
          <mesh name="Icosphere031" geometry={nodes.Icosphere031.geometry} material={nodes.Icosphere031.material} position={[-0.46, 4.86, 1.01]} rotation={[Math.PI, -0.79, Math.PI]} scale={[1.17, 0.86, 1.16]} />
          <mesh name="Icosphere032" geometry={nodes.Icosphere032.geometry} material={nodes.Icosphere032.material} position={[-0.8, 3.9, 0.43]} rotation={[Math.PI, -0.79, Math.PI]} scale={0.81} />
          <mesh name="Icosphere033" geometry={nodes.Icosphere033.geometry} material={nodes.Icosphere033.material} position={[-0.75, 3.29, 1.79]} rotation={[-1.83, -0.83, 2.81]} scale={0.61} />
          <mesh name="Icosphere034" geometry={nodes.Icosphere034.geometry} material={nodes.Icosphere034.material} position={[-1.71, 2.8, 1.6]} rotation={[-2.61, -1.31, 0.58]} scale={0.61} />
          <mesh name="Icosphere035" geometry={nodes.Icosphere035.geometry} material={nodes.Icosphere035.material} position={[-0.48, 3.45, -0.65]} rotation={[1.64, -0.79, -Math.PI]} scale={[0.81, 0.57, 0.81]} />
          <mesh name="Icosphere036" geometry={nodes.Icosphere036.geometry} material={nodes.Icosphere036.material} position={[0.85, 2.32, -0.99]} rotation={[2.35, 0.2, -1.47]} scale={[0.81, 1.25, 0.81]} />
        </group>
        <group name="Plane001" position={[11.16, 1.88, 2.02]} rotation={[0, -0.64, 0]} scale={12.24} />
        <group name="Plane002" position={[-10.4, 1.84, 5.42]} scale={6.64}>
          <mesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} position={[-0.06, 2.34, 0.55]} rotation={[0, 0.39, 0]} scale={[0.63, 0.2, 0.63]} />
          <mesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} position={[-0.07, 2.53, -0.02]} rotation={[0, 0.39, 0]} scale={[0.36, 0.2, 0.36]} />
          <mesh name="Icosphere003" geometry={nodes.Icosphere003.geometry} material={nodes.Icosphere003.material} position={[-0.52, 2.38, 0.29]} rotation={[0, 1.4, 0]} scale={[0.44, 0.2, 0.44]} />
          <mesh name="Icosphere004" geometry={nodes.Icosphere004.geometry} material={nodes.Icosphere004.material} position={[-0.57, 2.3, -0.28]} rotation={[0, 1.4, 0]} scale={[0.44, 0.2, 0.44]} />
          <mesh name="Icosphere005" geometry={nodes.Icosphere005.geometry} material={nodes.Icosphere005.material} position={[-0.17, 2.28, -0.8]} rotation={[0, -0.09, 0]} scale={[0.44, 0.2, 0.44]} />
          <mesh name="Icosphere006" geometry={nodes.Icosphere006.geometry} material={nodes.Icosphere006.material} position={[-0.04, 2.24, -0.33]} rotation={[0, -0.09, 0]} scale={[0.44, 0.2, 0.44]} />
          <mesh name="Icosphere007" geometry={nodes.Icosphere007.geometry} material={nodes.Icosphere007.material} position={[0.55, 2.24, -0.01]} rotation={[0, -0.09, 0]} scale={[0.44, 0.2, 0.44]} />
        </group>
        <group name="Plane039" position={[-3.4, 1.84, 11.42]} rotation={[0, -0.19, 0]} scale={6.64} />
        <mesh name="Original001" geometry={nodes.Original001.geometry} material={nodes.Original001.material} position={[10.04, 2.9, -6.22]} rotation={[0, 1.28, 0]} scale={0.83}>
          <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} position={[-0.12, 6.84, 0.02]} rotation={[0, 0.37, 0]} scale={3.11} />
          <mesh name="Plane013_1" geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} position={[-0.12, 6.84, 0.02]} rotation={[0, -0.81, 0]} scale={3.11} />
          <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} position={[-0.12, 6.84, 0.02]} rotation={[Math.PI, -1.21, Math.PI]} scale={3.11} />
          <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={nodes.Plane015.material} position={[-0.12, 6.84, 0.02]} rotation={[Math.PI, -0.22, Math.PI]} scale={3.11} />
          <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={nodes.Plane016.material} position={[-0.12, 6.84, 0.02]} rotation={[-Math.PI, 0.59, -Math.PI]} scale={3.11} />
          <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={nodes.Plane017.material} position={[-0.12, 6.84, 0.02]} rotation={[0, 1.43, 0]} scale={3.11} />
          <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={nodes.Plane018.material} position={[-0.09, 7.06, 0.23]} rotation={[0, -1.41, 0.53]} scale={3.11} />
          <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={nodes.Plane019.material} position={[-0.44, 7.06, 0.1]} rotation={[-Math.PI, -0.72, -2.61]} scale={3.11} />
          <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={nodes.Plane020.material} position={[-0.38, 7.06, -0.14]} rotation={[Math.PI, 0.44, -2.61]} scale={3.11} />
          <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={nodes.Plane021.material} position={[0.01, 7.06, -0.22]} rotation={[0, 1.51, 0.53]} scale={3.11} />
          <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={nodes.Plane022.material} position={[0.07, 7.07, 0.02]} rotation={[0, 0.12, 0.53]} scale={3.11} />
        </mesh>
        <mesh name="Icosphere037" geometry={nodes.Icosphere037.geometry} material={nodes.Icosphere037.material} position={[11.43, 8.64, 1.95]} rotation={[0, -0.64, 0]} scale={2.39} />
        <mesh name="Icosphere038" geometry={nodes.Icosphere038.geometry} material={nodes.Icosphere038.material} position={[12.42, 7.43, 2.66]} rotation={[0, 0.93, 0]} scale={0.96} />
        <mesh name="Icosphere039" geometry={nodes.Icosphere039.geometry} material={nodes.Icosphere039.material} position={[12.36, 7.23, 0.97]} rotation={[0, -0.64, 0]} scale={1.92} />
        <mesh name="Icosphere040" geometry={nodes.Icosphere040.geometry} material={nodes.Icosphere040.material} position={[11.54, 7.91, 4.65]} rotation={[-2.18, -1.32, 1.07]} scale={2.39} />
        <mesh name="Floor" geometry={nodes.Floor.geometry} material={materials.TieDyeFloor} position={[0, -0.02, -0.01]} scale={[13, 0.35, 13]} />
        <group name="Tree5" position={[-3.4, -0.02, 11.42]} rotation={[0, -0.19, 0]} scale={6.64}>
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials.TieDyeTree} />
          <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials.TieDyeTree} />
          <mesh name="Plane003_3" geometry={nodes.Plane003_3.geometry} material={materials.TieDyeTree} />
          <mesh name="Plane003_4" geometry={nodes.Plane003_4.geometry} material={materials.TieDyeTree} />
          <mesh name="Plane003_5" geometry={nodes.Plane003_5.geometry} material={materials.TieDyeTree} />
        </group>
        <group name="Tree5001" position={[10.98, -0.02, -5.22]} rotation={[-Math.PI, 0.89, -Math.PI]} scale={6.64}>
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials.TieDyeTree} />
          <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials.TieDyeTree} />
          <mesh name="Plane003_3" geometry={nodes.Plane003_3.geometry} material={materials.TieDyeTree} />
          <mesh name="Plane003_4" geometry={nodes.Plane003_4.geometry} material={materials.TieDyeTree} />
          <mesh name="Plane003_5" geometry={nodes.Plane003_5.geometry} material={materials.TieDyeTree} />
        </group>
        <mesh name="Tree4" geometry={nodes.Tree4.geometry} material={materials.TieDyeTree} position={[-0.01, 0.02, -10.71]} rotation={[-3.01, 0.81, Math.PI]} scale={3.64} />
        <mesh name="Tree3" geometry={nodes.Tree3.geometry} material={materials.TieDyeTree} position={[-10.4, -0.02, 5.42]} scale={6.64} />
        <mesh name="Tree3001" geometry={nodes.Tree3001.geometry} material={materials.TieDyeTree} position={[6.91, -0.02, 8.53]} rotation={[0, -1.43, 0]} scale={6.64} />
        <mesh name="Sun" geometry={nodes.Sun.geometry} material={materials['Material.001']} position={[27, 3, -13.53]} scale={4.08} />
        <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials.TieDyeTree} position={[10.48, 0.01, 2.94]} rotation={[0, -0.64, 0]} scale={17.52} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.TieDyeTree} position={[5.18, 0.01, 9.75]} rotation={[Math.PI, -1.04, Math.PI]} scale={12.24} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.TieDyeTree} position={[-7.45, 0.01, 8.75]} rotation={[0, 0.65, 0]} scale={12.24} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.TieDyeTree} position={[0.08, 1.03, 11.16]} scale={0.83} />
        <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials.TieDyeTree} position={[-10.56, 8.22, -1.15]} rotation={[0, -0.14, 0.53]} scale={3.23} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.TieDyeTree} position={[-8.04, 1.03, -6.44]} rotation={[0, 1.28, 0]} scale={0.67} />
        <mesh name="Icosphere008" geometry={nodes.Icosphere008.geometry} material={materials.TieDyeTree} position={[2.21, 0.16, -10.46]} />
        <mesh name="Icosphere009" geometry={nodes.Icosphere009.geometry} material={materials.TieDyeTree} position={[8.75, -0.02, -7.39]} scale={2.95} />
        <mesh name="Icosphere010" geometry={nodes.Icosphere010.geometry} material={materials.TieDyeTree} position={[5.96, 1.27, -9.7]} rotation={[-Math.PI, 0, 0]} scale={2.2} />
        <mesh name="Icosphere011" geometry={nodes.Icosphere011.geometry} material={materials.TieDyeTree} position={[5.22, 0.64, -7.34]} rotation={[-Math.PI, 0, 0]} scale={-0.76} />
        <mesh name="Icosphere012" geometry={nodes.Icosphere012.geometry} material={materials.TieDyeTree} position={[-7.61, 0.15, 4.55]} rotation={[0, -0.32, 0]} scale={2.95} />
        <mesh name="Icosphere013" geometry={nodes.Icosphere013.geometry} material={materials.TieDyeTree} position={[-9.53, 1.44, 1.48]} rotation={[-Math.PI, 0.32, 0]} scale={2.2} />
        <mesh name="Icosphere014" geometry={nodes.Icosphere014.geometry} material={materials.TieDyeTree} position={[8.75, -0.02, -7.39]} scale={2.95} />
        <mesh name="Icosphere015" geometry={nodes.Icosphere015.geometry} material={materials.TieDyeTree} position={[8.75, -0.02, -7.39]} scale={2.95} />
        <mesh name="Icosphere016" geometry={nodes.Icosphere016.geometry} material={materials.TieDyeTree} position={[8.75, -0.02, -7.39]} scale={2.95} />
        <mesh name="Icosphere017" geometry={nodes.Icosphere017.geometry} material={materials.TieDyeTree} position={[8.75, -0.02, -7.39]} scale={2.95} />
        <mesh name="Icosphere018" geometry={nodes.Icosphere018.geometry} material={materials.TieDyeTree} position={[8.75, -0.02, -7.39]} scale={2.95} />
        <mesh name="Icosphere019" geometry={nodes.Icosphere019.geometry} material={materials.TieDyeTree} position={[5.96, 1.27, -9.7]} rotation={[-Math.PI, 0, 0]} scale={2.2} />
      </group>
    </group>
  )
}

useGLTF.preload('static/Diorama/Diorama.gltf')
