/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: patrix (https://sketchfab.com/patrix)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/forest-demo-1269b7e00f9d4ce09931c0c95967bc33
title: Forest Demo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Forest({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/static/Forest/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={3}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.29}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.forest_forest_0.geometry} material={materials.forest} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/static/Forest/scene.gltf')
