/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 japanese_forest.glb
Author: Jesus aponza (https://sketchfab.com/Jesusaponza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-forest-2454c5c1e37941d6904a1ccb1e0ec154
Title: japanese forest
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function JapaneseForest(props) {
  const { nodes, materials } = useGLTF('static/japanese_forest.glb')
  return (
    <group {...props} dispose={null} scale={.1}>
      <group position={[-635.06, 16.87, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.den_tr_01_bark_0.geometry} material={materials.bark} />
        <mesh geometry={nodes.den_tr_01_leaves01b_0.geometry} material={materials.leaves01b} />
      </group>
      <group position={[112.57, 252.16, 218.3]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.den_tr_02_bark_0.geometry} material={materials.bark} />
        <mesh geometry={nodes.den_tr_02_leaves01b_0.geometry} material={materials.leaves01b} />
      </group>
      <group position={[640.31, 846.12, -1492.25]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.den_tr_03_bark_0.geometry} material={materials.bark} />
        <mesh geometry={nodes.den_tr_03_leaves01b_0.geometry} material={materials.leaves01b} />
      </group>
      <group position={[-294.73, 135.8, -552.08]} rotation={[-0.73, 0.4, 1.2]} scale={113.82}>
        <mesh geometry={nodes.weed_grass__leaves01b_0.geometry} material={materials.leaves01b} />
        <mesh geometry={nodes.weed_grass__leaves01b_0_1.geometry} material={materials.leaves01b} />
        <mesh geometry={nodes.weed_grass__leaves01b_0_2.geometry} material={materials.leaves01b} />
        <mesh geometry={nodes.weed_grass__leaves01b_0_3.geometry} material={materials.leaves01b} />
        <mesh geometry={nodes.weed_grass__leaves01b_0_4.geometry} material={materials.leaves01b} />
        <mesh geometry={nodes.weed_grass__leaves01b_0_5.geometry} material={materials.leaves01b} />
        <mesh geometry={nodes.weed_grass__leaves01b_0_6.geometry} material={materials.leaves01b} />
        <mesh geometry={nodes.weed_grass__leaves01b_0_7.geometry} material={materials.leaves01b} />
        <mesh geometry={nodes.weed_grass__leaves01b_0_8.geometry} material={materials.leaves01b} />
      </group>
      <mesh geometry={nodes.gorund_ground_text_0.geometry} material={materials.ground_text} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Icosphere_ground_text_0.geometry} material={materials.ground_text} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('static/japanese_forest.glb')
