/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 mountain.glb
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mountain-and-river-scroll-dd37769bdc0148a988535f893d01c551
Title: Mountain And River Scroll
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mountain(props) {
  const { nodes, materials } = useGLTF('static/mountain.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.06}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Accesories_VertexCollor_0.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_1.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_2.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_3.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_4.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_5.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_6.geometry} material={materials.VertexCollor} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Outline_VertexCollorBackFace_0.geometry} material={materials.VertexCollorBackFace} />
          <mesh geometry={nodes.Outline_VertexCollorBackFace_0_1.geometry} material={materials.VertexCollorBackFace} />
        </group>
        <mesh geometry={nodes.Plane001_Material_0.geometry} material={materials.Material} position={[-10137.57, 3446.38, 939.94]} rotation={[-1.56, 0, 3.14]} scale={113.24} />
        <mesh geometry={nodes.Plane003_Material001_0.geometry} material={materials['Material.001']} position={[-10016.21, 3757.47, -3755.64]} rotation={[-1.58, 0, Math.PI]} scale={70.81} />
        <mesh geometry={nodes.Main_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('static/mountain.glb')
