/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 neon_sign.glb 
Author: urbanmasque (https://sketchfab.com/urbanmasque)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neon-sign-d97be184a0c44efda93ea28421489191
Title: Neon Sign
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { a } from "@react-spring/three";
import { useSpring } from "@react-spring/core";

export function NeonSign({setSelected,selected,...props}) {
  const { nodes, materials } = useGLTF('static/neon_sign.glb')
  useEffect(()=>{
    setAPosition(false)
    setBPosition(false)
    setCPosition(false)
    setDPosition(false)
  },[])
  let [aPosition,setAPosition] = useState(true);
  let [bPosition,setBPosition] = useState(true);
  let [cPosition,setCPosition] = useState(true);
  let [dPosition,setDPosition] = useState(true);


   const changeAPosition = () =>{
    setAPosition(!aPosition)
  }

  const changeBPosition = () =>{
  setBPosition(!bPosition)
  }

  const changeCPosition = () =>{
  setCPosition(!cPosition)
  }
  
  const changeDPosition = () =>{
  setDPosition(!dPosition)
  }
  const  springA  = useSpring({
    z: aPosition? [0,20,-15 ]:[0,5,-15 ],
    config:{ mass: .85, tension: 390, friction: 15 }
  })
  const  springB  = useSpring({
    z: bPosition? [0,20,15 ]:[ 0,5,15 ],
    config:{ mass: .85, tension: 390, friction: 15 }
  })
    const  springC  = useSpring({
    z: cPosition? [-15,20,0 ]:[-15,5,0],
    config:{ mass: .85, tension: 390, friction: 15}
  })
    const  springD  = useSpring({
    z: dPosition? [15,20,0 ]:[15,5,0],
    config:{ mass: .85, tension: 390, friction: 15 }
  })
  const springE = useSpring({
    z: selected === null ? [0,0,0 ]:[0,10,0 ],
    rotation: selected === null ? [0,0,0 ]:[0,Math.PI,0 ],
    config:{ mass: .85, tension: 100, friction: 25 }
  })
  return (
    <a.group position={springE.z} rotation={springE.rotation} {...props} dispose={null}>
      <a.group onClick={()=>setSelected("Home")} rotation={[Math.PI /1.5,Math.PI/1.04 , 1/5]} position={springA.z} scale={5.377}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.003']} />
        <lineSegments geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
      </a.group>
      <a.group onClick={()=>setSelected("Project")} rotation={[-Math.PI /1.5,-1/8 , 1/5]} position={springB.z} scale={5.377}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.003']} />
        <lineSegments geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
      </a.group>
      <a.group onClick={()=>setSelected("Contact")} rotation={[Math.PI /2.18,Math.PI/1.2 , Math.PI/1.8]} position={springC.z} scale={5.377}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.003']} />
        <lineSegments geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
      </a.group>
      <a.group onClick={()=>setSelected(null)} rotation={[Math.PI /1.9,-Math.PI/1.2 , -Math.PI/2.4]} position={springD.z} scale={5.377}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.003']} />
        <lineSegments geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
      </a.group>
    </a.group>
  )
}

useGLTF.preload('static/neon_sign.glb')
